#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MODE_FORWARD 1
#define MODE_STOP 0
#define MODE_BACKWARD -1
#define BUTTON4 4
#define BUTTON2 2
#define NO_BUTTON 0
#define PRESSED 1
#define NOT_PRESSED 0

#include "JoystickDriver.c"

task main()
{

	int leftValue = 0, rightValue = 0;

	int trackMode = MODE_STOP, lastCondition = NOT_PRESSED;

	// init(); PLACEHOLDER: TODO: IMPLEMENT INIT()

	while(true) {
		getJoystickSettings(joystick);

		leftValue = joystick.joy1_y1;
		rightValue = joystick.joy1_y2;

		motor[leftMotor] = leftValue;
		motor[rightMotor] = rightValue;

		if (joy1Btn(4) == PRESSED) {
			if (lastCondition == NO_BUTTON || lastCondition == BUTTON2) {
				if (trackMode == MODE_FORWARD) {
					trackMode = MODE_STOP;
				}
				else {
					trackMode = MODE_FORWARD;
				}
			}
			lastCondition = BUTTON4;
		} else if (joy1Btn(2) == PRESSED) {
			if (lastCondition == NO_BUTTON || lastCondition == BUTTON4) {
				if (trackMode == MODE_BACKWARD) {
					trackMode = MODE_STOP;
				} else {
					trackMode = MODE_BACKWARD;
				}
			}
			lastCondition = BUTTON2;
		}	else {
			lastCondition = NO_BUTTON;
		}

		if (trackMode == MODE_FORWARD) {
			motor[motorF] = 100;
			motor[motorG] = 100;
		} else if (trackMode == MODE_BACKWARD) {
			motor[motorF] = -100;
			motor[motorG] = -100;
		}	else {
			motor[motorF] = 0;
			motor[motorG] = 0;
		}
	}
}
