#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{

	int leftValue = 0, rightValue = 0;

	int trackMode = 0, lastCondition = 0;

	// init(); PLACEHOLDER: TODO: IMPLEMENT INIT()

	while(true) {
		getJoystickSettings(joystick);

		leftValue = joystick.joy1_y1;
		rightValue = joystick.joy1_y2;

		motor[leftMotor] = leftValue;
		motor[rightMotor] = rightValue;

		if (joy1Btn(4) == 1) {
			if (lastCondition == 0 || lastCondition == 2) {
				if (trackMode == 1) {
					trackMode = 0;
				}
				else {
					trackMode = 1;
				}
			}
			lastCondition = 4;
		} else if (joy1Btn(2) == 1) {
			if (lastCondition == 0 || lastCondition == 4) {
				if (trackMode == -1) {
					trackMode = 0;
				} else {
					trackMode = -1;
				}
			}
			lastCondition = 2;
		}	else {
			lastCondition = 0;
		}

		if (trackMode == 1) {
			motor[motorF] = 100;
			motor[motorG] = 100;
		} else if (trackMode == -1) {
			motor[motorF] = -100;
			motor[motorG] = -100;
		}	else {
			motor[motorF] = 0;
			motor[motorG] = 0;
		}
	}
}
